# .github/workflows/TestWorkflow.yml
name: Render en Append Test Template

on:
  workflow_dispatch:
    inputs:
      resource_name:
        description: 'De interne Terraform-resource-naam (bv. my_share)'
        required: true
      resource_attribute_name:
        description: 'De waarde voor het attribuut “name” in de resource (bv. my_share)'
        required: true

jobs:
  render-and-append:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installeer Jinja2 CLI
        run: |
          python3 -m pip install --upgrade pip
          pip3 install jinja2-cli

      - name: Render test.tf.j2 en append naar test.tf
        run: |
          jinja2 .github/workflows/templates/test.tf.j2 \
            -D resource_name="${{ github.event.inputs.resource_name }}" \
            -D resource_attribute_name="${{ github.event.inputs.resource_attribute_name }}" \
            >> test.tf

      - name: Toon begin van test.tf voor debug
        run: head -n 20 test.tf
