# .github/workflows/test3Workflow.yml
name: Render and Append Recipients & Shares

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      payload:
        description: |
          A single JSON document with two top-level arrays:  
          {
            "recipients": [ ... ],  
            "shares": [ ... ]  
          }
        required: true
        type: string

jobs:
  render-and-append:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install Jinja2 CLI
        run: |
          python3 -m pip install --upgrade pip
          pip3 install jinja2-cli

      - name: Save payload to file
        run: |
          echo '${{ github.event.inputs.payload }}' > data.json

      - name: Render & append recipients
        run: |
          jinja2 .github/workflows/templates/Test3_recipients.tf.j2 data.json \
            --format json >> Test3_recipients.tf

      - name: Render & append shares
        run: |
          jinja2 .github/workflows/templates/Test3_shares.tf.j2 data.json \
            --format json >> Test3_shares.tf

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Test3_recipients.tf Test3_shares.tf
          git diff --cached --quiet || \
            git commit -m "ci: append recipients and shares"
          git push