# .github/workflows/TestWorkflow.yml
name: Render and Append Test Template

# 1) Grant write permissions so the job can push changes
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      resource_name:
        description: 'Internal Terraform resource name (e.g. my_share)'
        required: true
      resource_attribute_name:
        description: 'Value for the resource "name" attribute (e.g. my_share)'
        required: true

jobs:
  render-and-append:
    runs-on: ubuntu-latest
    steps:
      # 2) Checkout with push rights
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      # 3) Install Jinja2 CLI
      - name: Install Jinja2 CLI
        run: |
          python3 -m pip install --upgrade pip
          pip3 install jinja2-cli

      # 4) Render the template and append to your target file
      - name: Render and append Test_file_to_be_filled.tf
        run: |
          jinja2 .github/workflows/templates/Test_template.tf.j2 \
            -D resource_name="${{ github.event.inputs.resource_name }}" \
            -D resource_attribute_name="${{ github.event.inputs.resource_attribute_name }}" \
            >> Test_file_to_be_filled.tf

      # 5) Commit & push back to repo
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Test_file_to_be_filled.tf
          git diff --cached --quiet || git commit -m "ci: auto-append Test_file_to_be_filled.tf (${{ github.event.inputs.resource_name }})"
          git push
